---
- name: "update apt packages."
  become: true
  apt:
    update_cache: true

- name: "upgrade packages"
  become: true
  apt:
    upgrade: true

- name: "remove dependencies that are no longer required"
  become: true
  apt:
    autoremove: true

- name: "install nodejs and npm"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: present
    update_cache: true

- name: "install n"
  become: true
  npm:
    name: n
    global: true
    production: true

- name: "install nodejs 13.8.0"
  become: true
  command: n 13.8.0
  changed_when: false

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: true
    production: true
    state: present
