---
- name: "copy backend binaries"
  become: true
  synchronize:
    src: ../../backend/dist
    dest: /home/ubuntu/backend-supe
    recursive: true

- name: "copy node_modules"
  become: true
  synchronize:
    src: ../../backend/node_modules
    dest: /home/ubuntu/backend-supe
    recursive: true

- name: "delete anything that might already be running"
  become: true
  command: pm2 delete all
  ignore_errors: true

- name: "start server"
  become: true
  command: pm2 start -f ./main.js
  args:
    chdir: /home/ubuntu/backend-supe/dist
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: "{{ TYPEORM_CONNECTION }}"
    TYPEORM_MIGRATIONS_DIR: "{{ TYPEORM_MIGRATIONS_DIR }}"
    TYPEORM_MIGRATIONS: "{{ TYPEORM_MIGRATIONS }}"
    TYPEORM_ENTITIES: "{{ TYPEORM_ENTITIES }}"
    TYPEORM_HOST: "{{ TYPEORM_HOST }}"
    TYPEORM_PORT: "{{ TYPEORM_PORT }}"
    TYPEORM_USERNAME: "{{ TYPEORM_USERNAME }}"
    TYPEORM_PASSWORD: "{{ TYPEORM_PASSWORD }}"
    TYPEORM_DATABASE: "{{ TYPEORM_DATABASE }}"
