---
- name: "copy backend"
  become: true
  synchronize:
    src: /root/project/backend
    dest: /home/ubuntu
    recursive: true

- name: "copy node_modules"
  become: true
  synchronize:
    src: /home/circleci/project/backend/node_modules
    dest: /home/ubuntu/backend
    recursive: true

- name: "use pm2 to run the node server"
  shell: |
    cd /home/ubuntu/backend
    pm2 start -f dist/main.js
