---
- name: "copy backend binaries"
  become: true
  synchronize:
    src: /root/project/backend/dist
    dest: /home/ubuntu/backend-supe
    recursive: true

- name: "copy node_modules"
  become: true
  synchronize:
    src: /home/circleci/project/backend/node_modules
    dest: /home/ubuntu/backend-supe
    recursive: true

- name: "delete anything that might already be running"
  become: true
  command: pm2 delete all
  ignore_errors: true

- name: "use pm2 to run the node server"
  shell: |
    cd /home/ubuntu/backend-supe
    pm2 start npm -- run "start:dev"
